corda/djvm

- build.gradle
- djvm/build.gradle
- djvm/cli/build.gradle
- gradle.properties
Mainly to test the DJVM's TeamCity integration.
> Small enhancement to the DJVM project.

- djvm/src/main/kotlin/net/corda/djvm/analysis/AnalysisConfiguration.kt
- djvm/src/main/kotlin/net/corda/djvm/analysis/SourceLocation.kt
- djvm/src/main/kotlin/net/corda/djvm/code/EmitterModule.kt
- djvm/src/main/kotlin/net/corda/djvm/code/Types.kt
- djvm/src/main/kotlin/net/corda/djvm/rules/implementation/DisallowNonDeterministicMethods.kt
- djvm/src/main/kotlin/net/corda/djvm/rules/implementation/HandleExceptionUnwrapper.kt
- djvm/src/main/kotlin/net/corda/djvm/rules/implementation/RewriteClassMethods.kt
- djvm/src/main/kotlin/net/corda/djvm/rules/implementation/RewriteObjectMethods.kt
- djvm/src/main/kotlin/net/corda/djvm/rules/implementation/StringConstantWrapper.kt
- djvm/src/main/kotlin/net/corda/djvm/rules/implementation/ThrowExceptionWrapper.kt
- djvm/src/test/kotlin/net/corda/djvm/analysis/ClassResolverTest.kt
String constants are apparently a Good Thing :-).
> Declare sandbox.java.lang.DJVM class's internal name as a string constant.

- djvm/cli/build.gradle
- djvm/cli/src/main/kotlin/net/corda/djvm/tools/cli/VersionProvider.kt
> Fix djvm -V for CLI tool.

- djvm/src/main/kotlin/net/corda/djvm/execution/DeterministicSandboxExecutor.kt
- djvm/src/main/kotlin/net/corda/djvm/execution/Executor.kt
- djvm/src/main/kotlin/net/corda/djvm/execution/SandboxExecutor.kt
- djvm/src/main/kotlin/net/corda/djvm/execution/SandboxRawExecutor.kt
Simplify `SandboxRawExecutor` by introducing abstract base class `Executor`.
> CORDA-2871: Create abstract base Executor class.

- djvm-example/src/test/kotlin/com/example/testing/TestBase.kt
- djvm/src/main/kotlin/net/corda/djvm/SandboxConfiguration.kt
- djvm/src/main/kotlin/net/corda/djvm/analysis/AnalysisConfiguration.kt
- djvm/src/test/kotlin/net/corda/djvm/TestBase.kt
Allow a parent/child `AnalysisConfiguration` to create a parent/child `SandboxConfiguration`.
> CORDA-2871: Provide high-level API for creating a SandboxConfiguration.

- djvm-example/src/main/kotlin/com/example/testing/CordaX500NameToSandbox.kt
- djvm-example/src/main/kotlin/com/example/testing/PartyToSandbox.kt
- djvm-example/src/test/kotlin/com/example/testing/CryptoTest.kt
- djvm/src/test/java/net/corda/djvm/execution/Base64Test.java
- djvm/src/test/java/net/corda/djvm/execution/DataInputStreamTest.java
- djvm/src/test/java/net/corda/djvm/execution/DatatypeConverterTest.java
- djvm/src/test/java/net/corda/djvm/execution/SandboxCloneableTest.java
- djvm/src/test/java/net/corda/djvm/execution/SandboxConcurrentHashMapTest.java
- djvm/src/test/java/net/corda/djvm/execution/SandboxStrictMathTest.java
- djvm/src/test/java/net/corda/djvm/execution/SandboxStringTest.java
- djvm/src/test/java/net/corda/djvm/execution/X500Tests.java
Prove that deserialising Corda `Party` instances is possible, and that Base64 encode/decode works in the sandbox too.
> Add tests for Base64 encode/decode, and sandboxing Corda Party instances.

- djvm-example/src/test/kotlin/com/example/testing/Executor.kt
- djvm/src/main/kotlin/net/corda/djvm/execution/SandboxRuntimeException.kt
- djvm/src/main/kotlin/net/corda/djvm/rewiring/SandboxClassLoader.kt
- djvm/src/main/kotlin/net/corda/djvm/rewiring/SandboxClassLoadingException.kt
- djvm/src/test/java/net/corda/djvm/WithJava.java
- djvm/src/test/java/net/corda/djvm/execution/BasicInputOutputTest.java
- djvm/src/test/java/net/corda/djvm/execution/SandboxStringTest.java
Tidy up implementation of the "basic task" lambdas and create `SandboxRuntimeException` base exception class.
> CORDA-2871: Tidy up basic input/output tasks.

- djvm/build.gradle
- djvm/src/main/java/sandbox/java/nio/ByteOrder.java
- djvm/src/main/kotlin/net/corda/djvm/analysis/AnalysisConfiguration.kt
- djvm/src/main/kotlin/net/corda/djvm/analysis/JavaNioBitsConfiguration.kt
- djvm/src/main/kotlin/net/corda/djvm/analysis/JavaTimeConfiguration.kt
- djvm/src/main/kotlin/sandbox/java/lang/DJVM.kt
- djvm/src/test/java/net/corda/djvm/execution/BitSetTest.java
Corda's serialisation engine requires `BitSet` support.
> CORDA-2871: Add support for java.util.BitSet.

- djvm/src/main/kotlin/net/corda/djvm/rules/implementation/DisallowNonDeterministicMethods.kt
There are three classes in `sun/security/x509` that need to access `Constructor` - list them explicitly.
> CORDA-2871: Fine-tune handling of reflection for X.509 classes.

- djvm/src/main/kotlin/net/corda/djvm/analysis/AnalysisConfiguration.kt
Refactor the `AnalysisConfigutation` class, which has been growing origanically for too long.
> NOTICK: Simplify construction of AnalysisConfiguration class.

- djvm/src/main/kotlin/net/corda/djvm/rewiring/SandboxClassLoader.kt
We only need to cache the `ByteCode` objects against the names used to define them. Re-use the `ClassLoader` built-in `findLoadedClass()` method to determine whether a class has been loaded already.
> CORDA-2871: Replace SandboxClassLoader's cache of LoadedClass with a cache of ByteCode.

- serialization/deserializers/src/main/kotlin/net/corda/djvm/serialization/deserializers/DescribeEnum.kt
- serialization/src/test/kotlin/net/corda/djvm/serialization/DeserializeEnumTest.kt
- serialization/src/test/kotlin/net/corda/djvm/serialization/TestBase.kt
Emphasise that the tests have two class loaders - a parent and a child.
> Minor cosmetic fixes.

- build.gradle
- djvm-example/build.gradle
- djvm-example/gradle.properties
- djvm-example/settings.gradle
- gradle.properties
Reassign the DJVM's Maven coordinates:
```
group: net.corda.djvm
artifact: corda-djvm
version: 1.0-SNAPSHOT
```
> Reset the DJVM's Maven coordinates to net.corda.djvm:corda-djvm:1.0-SNAPSHOT.

- djvm-example/src/main/kotlin/com/example/testing/VerifySignature.kt
- djvm-example/src/test/kotlin/com/example/testing/CryptoTest.kt
- djvm/src/main/kotlin/net/corda/djvm/rules/implementation/AlwaysUseExactMath.kt
- djvm/src/main/kotlin/sandbox/java/lang/DJVM.kt
- gradle.properties
Demonstrate verifying signatures inside the sandbox using Corda Crypto.
> Test verifying signatures inside the sandbox.

- djvm-example/gradle.properties
- gradle.properties
- JUnit -> 5.5.2
- Log4J2 -> 2.12.1
- AssertJ -> 3.13.2
- ClassGraph -> 4.8.47
- PicoCli -> 3.9.6
> Upgrade DJVM dependencies.

- build.gradle
- djvm-example/build.gradle
We almost certainly want this for code quality.
> Enable "warnings as errors" for Java and Kotlin compilation.

- djvm-example/gradle.properties
- serialization/build.gradle
The 4.4-SNAPSHOT artifacts have now arrived in the Artifactory - _use them!_
> Update to use Corda 4.4-SNAPSHOT.

- djvm/src/main/kotlin/net/corda/djvm/SandboxConfiguration.kt
Small refactor to make the code easier to read.
> Refactor names of initial sandbox classes into a private set.

- build.gradle
- djvm-example/build.gradle
- djvm-example/gradle/wrapper/gradle-wrapper.properties
- gradle/wrapper/gradle-wrapper.properties
Upgrade to the final Gradle 5.x release.
> NOTICK: Upgrade Gradle 5.6.3 -> 5.6.4.

- build.gradle
- djvm/src/main/kotlin/net/corda/djvm/rewiring/KotlinMetadataVisitor.kt
- djvm/src/main/kotlin/net/corda/djvm/rewiring/SandboxClassRemapper.kt
- gradle.properties
- Make some Gradle tasks lazy.
- Upgrade to Corda Gradle plugins 5.0.8.
- Turn some Kotlin constants into static final fields.
> Small tidy up for Gradle.

- djvm-example/build.gradle
- djvm-example/gradle.properties
- djvm/build.gradle
- djvm/secure/build.gradle
Help Gradle know what it can download from where in an attempt to optimise the build.
> NOTICK: Tell Gradle which artifacts to fetch from which repositories.

- djvm/src/main/java/sandbox/java/lang/Enum.java
- djvm/src/main/java/sandbox/java/util/Collections.java
- djvm/src/main/kotlin/sandbox/java/lang/DJVM.kt
The `enumConstantDirectory` should really be package private, but Kotlin does not support that. So ensure that it is at least immutable.
> Ensure that DJVM.enumConstantDirectory() returns an immutable map.

- build.gradle
- djvm-example/build.gradle
- djvm/build.gradle
- djvm/secure/build.gradle
Good Gradle hygiene means that we create as few tasks as possible when configuring the project.
> NOTICK: Use task configuration avoidance in build.gradle scripts.

- build.gradle
- djvm/build.gradle
- djvm/cli/build.gradle
- gradle.properties
- settings.gradle
- Corda Gradle plugins: 5.0.8 -> 5.0.11
- Artifactory: 4.16.0 -> 4.16.1
> NOTICK: Upgrade to Corda Gradle plugins 5.0.11.

- djvm-example/src/test/kotlin/com/example/testing/TestBase.kt
- djvm/build.gradle
- djvm/src/main/kotlin/sandbox/java/lang/DJVM.kt
- djvm/src/test/kotlin/net/corda/djvm/TestBase.kt
- Resolve some simple compiler warnings.
- Allow jars to be added to sandbox classpath for Java test cases.
> NOTICK: Minor tweaks to Gradle and testing.

- build.gradle
- djvm-example/build.gradle
- djvm-example/gradle/wrapper/gradle-wrapper.properties
- gradle/wrapper/gradle-wrapper.properties
- settings.gradle
Upgrade Gradle 6.6 -> 6.6.1.
Also upgrade these plugins:
- Gradle Enterprise: 3.4 -> 3.4.1
- Artifactory: 4.16.1 -> 4.17.1
> NOTICK: Upgrade to Gradle 6.6.1.

- djvm/src/main/kotlin/net/corda/djvm/SandboxConfiguration.kt
Fix for an unlikely edge-case: Ignore Java 9+ classes from multi-release jars that also contain META-INF/DJVM-preload tag.
Also respect the jar:/ URL format when parsing source URLs.
> CORDA-3925: Do not preload any Java 9+ files from multi-release jars.

- djvm/build.gradle
- gradle.properties
Use the Bnd's Gradle plugin's new support for lazy bnd instructions.
> NOTICK: Upgrade to Bnd 5.2.0

- gradle.properties
Upgrade the OSGi Bnd Tools 5.2.0 -> 5.3.0.
> NOTICK: Upgrade to Bnd 5.3.0.

- djvm/src/main/kotlin/net/corda/djvm/rules/implementation/DisallowUnsupportedApiVersions.kt
- gradle.properties
Upgrade ASM 9.0 -> 9.1.
[Release notes.](https://asm.ow2.io/versions.html)
> NOTICK: Upgrade to ASM 9.1.

- djvm-example/gradle.properties
- djvm/build.gradle
- djvm/osgi/test.bndrun
- djvm/src/main/kotlin/net/corda/djvm/rules/implementation/DisallowUnsupportedApiVersions.kt
- gradle.properties
- settings.gradle
Update versions of components and build tools:
- ASM 9.1 -> 9.2
- JUnit 5.7.1 -> 5.7.2
- JUnit Platform 1.7.1 -> 1.7.2
- Corda 4.8-SNAPSHOT -> 4.8
- Felix 6.0.4 -> 7.0.1
- Felix ConfigAdmin 1.9.20 -> 1.9.22
- OSGi 7.0.0 -> 8.0.0
Also generate KDocs using Dokka plugin.
> NOTICK: Upgrade component versions.

- djvm/src/main/kotlin/net/corda/djvm/rewiring/SandboxClassLoader.kt
- djvm/src/main/kotlin/net/corda/djvm/source/Sources.kt
- djvm/src/main/kotlin/net/corda/djvm/source/impl/SourceClassLoaderImpl.kt
- gradle.properties
- Remove unnecessary `null`-checks.
- Register the `SourceClassLoader` as being parallel-capable.
- Upgrade Corda Gradle plugins to 5.0.14.
> NOTICK: Optimise Kotlin code generation when calling to/from Java.

- djvm-example/gradle.properties
- djvm-example/src/test/kotlin/com/example/testing/TestBase.kt
- djvm/osgi/src/test/kotlin/com/example/osgi/testing/TestBase.kt
- djvm/osgi/test.bndrun
- djvm/secure/src/test/kotlin/com/example/testing/TestBase.kt
- djvm/src/test/kotlin/net/corda/djvm/SandboxConfigurationTest.kt
- djvm/src/test/kotlin/net/corda/djvm/TestBase.kt
- gradle.properties
- Corda 4.8.5 -> 4.8.6
- Corda Gradle plugins 5.0.14 -> 5.0.15
- SLF4J 1.7.32 -> 1.7.36
- Log4J 2.17.0 -> 2.17.1
- Logback 1.2.6 -> 1.2.10
- Felix 7.0.1 -> 7.0.3
- Use JUnit's `@TestInstance(PER_CLASS)` for test classes.
> NOTICK: Upgrade dependency versions,

- djvm-example/gradle.properties
- djvm/src/main/kotlin/net/corda/djvm/rules/implementation/DisallowUnsupportedApiVersions.kt
- djvm/src/test/kotlin/net/corda/djvm/DJVMExceptionTest.kt
- djvm/src/test/kotlin/net/corda/djvm/SyntheticExceptionCachingTest.kt
- djvm/src/test/kotlin/net/corda/djvm/analysis/ClassAndMemberVisitorTest.kt
- djvm/src/test/kotlin/net/corda/djvm/assertions/AssertionExtensions.kt
- djvm/src/test/kotlin/net/corda/djvm/assertions/AssertiveClassHierarchy.kt
- djvm/src/test/kotlin/net/corda/djvm/assertions/AssertiveClassHierarchyWithClass.kt
- djvm/src/test/kotlin/net/corda/djvm/assertions/AssertiveDJVMObject.kt
- djvm/src/test/kotlin/net/corda/djvm/assertions/AssertiveMessages.kt
- djvm/src/test/kotlin/net/corda/djvm/assertions/AssertiveReferenceMap.kt
- djvm/src/test/kotlin/net/corda/djvm/source/SourceClassLoaderTest.kt
- gradle.properties
- Corda 4.8.6 -> 4.9
- ASM 9.2 -> 9.3
- BouncyCastle 1.69 -> 1.70
- Bnd 6.2.0 -> 6.3.0
- OSGi Function 1.1.0 -> 1.2.0
- OSGi Promise 1.1.1 -> 1.2.0
- OSGi PushStream 1.0.1  -> 1.0.2
- Felix Log 1.2.4 -> 1.2.6
- Felix Logback 1.0.2 -> 1.0.6
- Logback 1.2.10 -> 1.2.11
- Log4J 2.17.1 -> 2.17.2
- AssertJ 3.20.2 -> 3.23.1
> NOTICK: Upgrade dependencies

- djvm-example/gradle.properties
- gradle.properties
Upgrades:
- Corda 4.9.3 -> 4.9.5
- Bnd 6.3.1 -> 6.4.0
- JUnit 5.9.0 -> 5.9.1
> NOTICK: Upgrade dependencies.

- build.gradle
- djvm-example/build.gradle
- djvm-example/gradle.properties
- djvm-example/gradle/wrapper/gradle-wrapper.properties
- gradle.properties
- gradle/wrapper/gradle-wrapper.properties
Upgrade the following components:
- Gradle 6.9.2 -> 6.9.3
- Corda 4.9.5 -> 4.10
- JUnit 5.9.1 -> 5.9.2
> NOTICK: Various upgrades.
