.gitignore, djvm/src/main/java/sandbox/java/lang/System.java, djvm/src/main/kotlin/net/corda/djvm/rules/implementation/RewriteClassMethods.kt, djvm/src/test/kotlin/net/corda/djvm/TestBase.kt, djvm/src/test/kotlin/net/corda/djvm/execution/SandboxExecutorTest.kt
The `ProtectionDomain` allows us to determine the source location of a `class` file, e.g. the URL of the JAR that contains it. This could theoretically allow us to determine whether or not we are running inside the sandbox. But regardless, there's no obvious way to map/wrap/transform a `java.security.ProtectionDomain` instance anyway so block this gap off.
=> Ensure that class ProtectionDomain cannot be accessed inside the sandbox.

djvm/build.gradle, djvm/cli/build.gradle
Seal the DJVM jars so that applications cannot provide their own versions of the template `sandbox.*` classes or tamper with the DJVM's working.
=> Seal the DJVM jar artifacts to preserve the sandbox integrity.

djvm/src/main/kotlin/net/corda/djvm/references/Member.kt, djvm/src/main/kotlin/net/corda/djvm/rules/implementation/AlwaysUseNonSynchronizedMethods.kt, djvm/src/main/kotlin/net/corda/djvm/rules/implementation/AlwaysUseStrictFloatingPointArithmetic.kt, djvm/src/main/kotlin/net/corda/djvm/rules/implementation/StubOutNativeMethods.kt, djvm/src/main/kotlin/net/corda/djvm/rules/implementation/StubOutReflectionMethods.kt
Some of these `ACC_xxx` flags have different meanings, depending on whether they're applied to methods or fields. So ensure that we're only modifying the byte-code as we intend.
=> Ensure that method-specific definition rules are not also accidentally applied to fields.

djvm/src/main/java/sandbox/java/lang/Runtime.java, djvm/src/main/java/sandbox/java/lang/StrictMath.java, djvm/src/main/kotlin/net/corda/djvm/analysis/AnalysisConfiguration.kt, djvm/src/main/kotlin/net/corda/djvm/rules/implementation/DisallowCatchingBlacklistedExceptions.kt
Allow the native methods of `java.lang.StrictMath` within the sandbox by wrapping them inside a template class.
=> Add support for java.lang.StrictMath and its native methods.

LICENSE
The `sandbox.java.*` and `sandbox.sun.*` classes in this project were created by referencing the OpenJDK8 source code. As a result, the DJVM inherits the OpenJDK's GPLv2 Open Source licence.
Using the DJVM under terms other than GPLv2 will require you to negotiate an alternate licence with the OpenJDK's copyright holder, namely Oracle Corporation.
=> Add GPLv2 Open Source licence to the DJVM.

djvm/src/main/java/sandbox/java/lang/Boolean.java, djvm/src/main/java/sandbox/java/lang/Byte.java, djvm/src/main/java/sandbox/java/lang/Character.java, djvm/src/main/java/sandbox/java/lang/DJVMThrowableWrapper.java, djvm/src/main/java/sandbox/java/lang/Double.java, djvm/src/main/java/sandbox/java/lang/Enum.java, djvm/src/main/java/sandbox/java/lang/Float.java, djvm/src/main/java/sandbox/java/lang/Integer.java, djvm/src/main/java/sandbox/java/lang/Long.java, djvm/src/main/java/sandbox/java/lang/Object.java, djvm/src/main/java/sandbox/java/lang/Short.java, djvm/src/main/java/sandbox/java/lang/String.java, djvm/src/main/java/sandbox/java/lang/Throwable.java, djvm/src/main/kotlin/net/corda/djvm/SandboxConfiguration.kt, djvm/src/main/kotlin/net/corda/djvm/analysis/AnalysisConfiguration.kt, djvm/src/main/kotlin/net/corda/djvm/rules/implementation/DisallowSandboxMethods.kt, djvm/src/test/java/net/corda/djvm/execution/MaliciousClassTest.java
Do not load classes that implement methds `toDJVMString()` or `fromDJVM()` because these methods have special significance inside the sandbox.
=> Reject classes that implement internal DJVM-specific methods.

djvm/cli/src/main/kotlin/net/corda/djvm/tools/cli/ClassCommand.kt, djvm/src/main/kotlin/net/corda/djvm/execution/DeterministicSandboxExecutor.kt, djvm/src/main/kotlin/net/corda/djvm/execution/IsolatedTask.kt, djvm/src/main/kotlin/net/corda/djvm/execution/SandboxExecutor.kt, djvm/src/main/kotlin/net/corda/djvm/messages/MessageCollection.kt, djvm/src/main/kotlin/net/corda/djvm/source/SourceClassLoader.kt, djvm/src/test/kotlin/net/corda/djvm/execution/SandboxExecutorTest.kt
Allow DJVM to analyse classes on-the-fly instead of trying to do everything up-front. Not every referenced class is guaranteed to exist, but we're not going to be executing every code path either.
=> CORDA-2871: Allow DJVM to analyse classes on-the-fly.

djvm/src/main/kotlin/net/corda/djvm/analysis/AnalysisConfiguration.kt, djvm/src/main/kotlin/net/corda/djvm/code/EmitterModule.kt, djvm/src/main/kotlin/net/corda/djvm/code/Types.kt, djvm/src/main/kotlin/net/corda/djvm/costing/ThresholdViolationError.kt, djvm/src/main/kotlin/net/corda/djvm/costing/TypedRuntimeCost.kt, djvm/src/main/kotlin/net/corda/djvm/rules/implementation/DisallowCatchingBlacklistedExceptions.kt, djvm/src/main/kotlin/net/corda/djvm/rules/implementation/DisallowNonDeterministicMethods.kt, djvm/src/main/kotlin/net/corda/djvm/rules/implementation/RewriteClassMethods.kt, djvm/src/main/kotlin/sandbox/RuntimeCostAccounter.kt, djvm/src/main/kotlin/sandbox/Task.kt, djvm/src/main/kotlin/sandbox/java/lang/DJVM.kt, djvm/src/main/kotlin/sandbox/net/corda/djvm/costing/RuntimeCostAccounter.kt, djvm/src/test/java/greymalkin/PureEvil.java, djvm/src/test/java/net/corda/djvm/Utilities.java, djvm/src/test/java/net/corda/djvm/execution/MaliciousClassLoaderTest.java, djvm/src/test/java/net/corda/djvm/execution/MaliciousClassTest.java, djvm/src/test/kotlin/net/corda/djvm/costing/RuntimeCostTest.kt, djvm/src/test/kotlin/net/corda/djvm/execution/SandboxExecutorTest.kt, djvm/src/test/kotlin/net/corda/djvm/rewiring/ClassRewriterTest.kt
We should not allow sandboxed code to obtain a reference to the DJVM's _own_ `ClassLoader`, because this might be used (somehow) to break out of the sandbox. So we do two things:
- Ensure that `ClassLoader.getParent()` always returns `null`.
- Restrict access to `ClassLoader` constructors! Arguably we don't expect sandboxed code to need to create new `ClassLoader` objects _at all_, but we can _tolerate_ the no-argument constructor for now.
- Convert `RuntimeCostAccounter` into a template class.
- Unpin `ThresholdViolationError` class.
=> CORDA-3045: Tighten rules around ClassLoader usage.

djvm/src/main/java/sandbox/java/lang/Object.java, djvm/src/main/kotlin/net/corda/djvm/analysis/AnalysisConfiguration.kt, djvm/src/main/kotlin/net/corda/djvm/code/EmitterModule.kt, djvm/src/main/kotlin/net/corda/djvm/code/Types.kt, djvm/src/main/kotlin/net/corda/djvm/rules/RuleViolationError.kt, djvm/src/main/kotlin/net/corda/djvm/rules/implementation/DisallowNonDeterministicMethods.kt, djvm/src/main/kotlin/net/corda/djvm/rules/implementation/DisallowOverriddenSandboxPackage.kt, djvm/src/main/kotlin/net/corda/djvm/rules/implementation/MemberRuleEnforcer.kt, djvm/src/main/kotlin/net/corda/djvm/rules/implementation/RewriteClassMethods.kt, djvm/src/main/kotlin/net/corda/djvm/source/SourceClassLoader.kt, djvm/src/main/kotlin/net/corda/djvm/validation/RuleContext.kt, djvm/src/main/kotlin/sandbox/RuntimeCostAccounter.kt, djvm/src/main/kotlin/sandbox/Task.kt, djvm/src/main/kotlin/sandbox/java/lang/DJVM.kt, djvm/src/test/java/net/corda/djvm/Utilities.java, djvm/src/test/java/net/corda/djvm/execution/MaliciousClassLoaderTest.java, djvm/src/test/java/net/corda/djvm/execution/MaliciousClassTest.java, djvm/src/test/java/net/corda/djvm/execution/SandboxThrowableJavaTest.java, djvm/src/test/kotlin/net/corda/djvm/TestBase.kt, djvm/src/test/kotlin/net/corda/djvm/execution/SandboxExecutorTest.kt, djvm/src/test/kotlin/net/corda/djvm/rewiring/ClassRewriterTest.kt
- Stop mapping the `RuleViolationError` exception into the `sandbox.*` package space because it leaks the application classloader into the sandbox. Pinned classes can now be locked down as a "testing" feature.
- Fix a bug where the static `SandboxRuntimeContext` reference inside `RuntimeCostAccounter` could become stale. This will be better fixed by [CORDA-2877](https://r3-cev.atlassian.net/browse/CORDA-2877).
- Simplify the `BootstrapClassLoader`/`SourceClassLoader` configuration when creating sandboxes.
=> CORDA-3045: Remove the final pinned class.

djvm/cli/build.gradle
Ensure we distribute modified OpenJDK code _with_ its licence.
=> Include DJVM's GPLv2+CPE licence file inside CLI's ZIP distribution.

djvm/build.gradle, djvm/src/main/java/sandbox/java/lang/Thread.java, djvm/src/main/java/sandbox/java/util/ArrayList.java, djvm/src/main/java/sandbox/java/util/Date.java, djvm/src/main/java/sandbox/java/util/concurrent/TimeUnit.java, djvm/src/main/java/sandbox/java/util/concurrent/atomic/AtomicInteger.java, djvm/src/main/java/sandbox/java/util/concurrent/locks/Condition.java, djvm/src/main/java/sandbox/java/util/concurrent/locks/DJVMConditionObject.java, djvm/src/main/java/sandbox/java/util/concurrent/locks/Lock.java, djvm/src/main/java/sandbox/java/util/concurrent/locks/ReentrantLock.java, djvm/src/main/java/sandbox/java/util/function/IntBinaryOperator.java, djvm/src/main/java/sandbox/java/util/function/IntUnaryOperator.java, djvm/src/main/kotlin/net/corda/djvm/analysis/AnalysisConfiguration.kt, djvm/src/main/kotlin/sandbox/java/lang/DJVM.kt, djvm/src/test/kotlin/net/corda/djvm/execution/LinkedBlockingQueueTest.kt, djvm/src/test/kotlin/net/corda/djvm/execution/SandboxExecutorTest.kt
Corda requires SLF4J and SLF4J requires `LinkedBlockingQueue`, which in turn requires `AtomicInteger` and `ReentrantLock`.
=> CORDA-3067: Reimplement AtomicInteger and ReentrantLock for use inside the sandbox.

djvm-example/build.gradle, djvm-example/settings.gradle, djvm/build.gradle, djvm/src/main/java/sandbox/java/lang/System.java, djvm/src/main/java/sandbox/java/security/AccessControlException.java, djvm/src/main/kotlin/net/corda/djvm/analysis/AnalysisConfiguration.kt, djvm/src/main/kotlin/sandbox/java/lang/DJVM.kt, djvm/src/test/java/net/corda/djvm/execution/SecurityManagerTest.java
- Provide the sandbox example with a NOP implementation of SLF4J's `StaticLoggerBinder` class.
- Allow `SandboxClassLoadingException` instances to escape the sandbox unhindered.
- Stub out `System.setSecurityManager()` always to throw `AccessControlException`.
=> CORDA-3069: Allow SLF4J to initialise within the sandbox.

djvm-example/build.gradle
Ensure that `djvm-example` can find the DJVM jar artifact when executed as a composite Gradle project.
=> Ensure that DJVM project creates its artifact for composite build.

djvm-example/src/test/kotlin/com/example/testing/TestBase.kt, djvm/cli/src/main/kotlin/net/corda/djvm/tools/cli/ClassCommand.kt, djvm/src/main/kotlin/net/corda/djvm/analysis/AnalysisConfiguration.kt, djvm/src/main/kotlin/net/corda/djvm/source/SourceClassLoader.kt, djvm/src/test/kotlin/net/corda/djvm/TestBase.kt, djvm/src/test/kotlin/net/corda/djvm/source/SourceClassLoaderTest.kt
The DJVM cannot assume that it can use `URLClassLoader` for its sources, _particularly_ inside the SGX enclave. Abstract its uses away behind new `ApiSource` and `UserSource` interfaces.
=> CORDA-3097: Abstract the URLClassLoaders away behind some interfaces.

djvm/src/main/kotlin/net/corda/djvm/analysis/AnalysisConfiguration.kt, djvm/src/main/kotlin/net/corda/djvm/execution/SandboxRawExecutor.kt, djvm/src/main/kotlin/sandbox/TaskTypes.kt, djvm/src/main/kotlin/sandbox/java/lang/DJVM.kt, djvm/src/test/kotlin/net/corda/djvm/execution/SandboxExecutorTest.kt, djvm/src/test/kotlin/net/corda/djvm/execution/SandboxRawExecutorTest.kt
Provide an Executor that does not attempt to marshall its input and output objects between sandbox and non-sandbox types.
=> CORDA-2871: Add a RawTask that does not marshall its inputs and outputs.

djvm/src/main/kotlin/net/corda/djvm/source/SourceClassLoader.kt
A `ClassLoader` not based on `URLClassLoader` can probably implement `AutoCloseable` rather than `Closeable`.
=> CORDA-3097: Replace Closeable with AutoCloseable in Source interface.

build.gradle, djvm/build.gradle, djvm/src/main/java/sandbox/javax/security/auth/x500/DJVM.java, djvm/src/main/java/sandbox/javax/security/auth/x500/X500Principal.java, djvm/src/main/java/sandbox/sun/security/action/GetBooleanAction.java, djvm/src/main/java/sandbox/sun/security/x509/X500Name.java, djvm/src/main/kotlin/net/corda/djvm/analysis/AnalysisConfiguration.kt, djvm/src/main/kotlin/net/corda/djvm/code/EmitterModule.kt, djvm/src/main/kotlin/sandbox/java/lang/DJVM.kt, djvm/src/test/java/net/corda/djvm/execution/X500Tests.java, djvm/src/test/kotlin/net/corda/djvm/execution/BasicCryptoTest.kt, djvm/src/test/kotlin/net/corda/djvm/execution/SandboxExecutorTest.kt
We need `X500Principal` (and hence `X500Name`) inside the sandbox so that the DJVM can support `CordaX500Name`. Remove these classes internal use of reflection which was preventing them from initialising.
=> CORDA-3089: Support X500Principal and X500Name inside the sandbox.

djvm-example/build.gradle, djvm-example/src/main/kotlin/com/example/testing/DecodePublicKey.kt, djvm-example/src/test/kotlin/com/example/testing/CryptoTest.kt, djvm/src/main/kotlin/net/corda/djvm/rules/implementation/AlwaysUseExactMath.kt, djvm/src/main/kotlin/net/corda/djvm/rules/implementation/DisallowNonDeterministicMethods.kt, djvm/src/main/kotlin/sandbox/java/lang/DJVM.kt, djvm/src/test/kotlin/net/corda/djvm/execution/BasicCryptoTest.kt, djvm/src/test/kotlin/net/corda/djvm/execution/SandboxExecutorTest.kt
We need to be able to decode Corda's `PublicKey` instances within the DJVM's sandbox. Validate this for all of Corda's signature schemes.
=> CORDA-2871: Add support for BouncyCastle to DJVM for sake of Corda

djvm-example/src/main/kotlin/com/example/testing/PublicKeyDecoder.kt, djvm-example/src/main/kotlin/com/example/testing/PublicKeyFunction.kt, djvm-example/src/main/kotlin/com/example/testing/TransformPublicKey.kt, djvm-example/src/test/kotlin/com/example/testing/CryptoTest.kt, djvm-example/src/test/kotlin/com/example/testing/Executor.kt, djvm/src/main/java/sandbox/java/lang/String.java, djvm/src/main/kotlin/net/corda/djvm/analysis/AnalysisConfiguration.kt, djvm/src/main/kotlin/net/corda/djvm/source/SourceClassLoader.kt, djvm/src/test/java/net/corda/djvm/execution/DatatypeConverterTest.java, djvm/src/test/kotlin/net/corda/djvm/DJVMExceptionTest.kt, djvm/src/test/kotlin/net/corda/djvm/DJVMTest.kt, djvm/src/test/kotlin/net/corda/djvm/TaskExecutor.kt
Java 8 code typically uses the `printHexBinary` and `parseHexBinary` methods of `DatatypeConverter` to convert between `byte[]` and hexadecimal strings, c.f. Corda's `ByteArray.toHexString()` and `String.parseAsHex()` methods.
Support `DatatypeConverter` inside the sandbox by initialising it with a default `DatatypeFactory` instance.
=> CORDA-2871: Add basic DatatypeFactory for hex-to-binary conversions.

djvm-example/build.gradle
There is no need to set the `changing = true` flag because Gradle deduces this from the `SNAPSHOT` version.
=> A SNAPSHOT version is automatically "changing".

djvm/src/test/java/net/corda/djvm/execution/SandboxExecutorJavaTest.java, djvm/src/test/kotlin/net/corda/djvm/execution/SandboxExecutorTest.kt
Fix cut-n-paste issue by renaming `contractEcecutor` to `executor`.
Add test for accessing `Class<?>` using `::class.java`.
=> Test classes available using ::class.java.

djvm-example/build.gradle, djvm-example/src/test/kotlin/com/example/testing/LocalSerialization.kt, djvm/build.gradle, djvm/src/main/java/sandbox/java/time/DJVM.java, djvm/src/main/java/sandbox/java/time/Duration.java, djvm/src/main/java/sandbox/java/time/Instant.java, djvm/src/main/java/sandbox/java/time/LocalDate.java, djvm/src/main/java/sandbox/java/time/LocalDateTime.java, djvm/src/main/java/sandbox/java/time/LocalTime.java, djvm/src/main/java/sandbox/java/time/MonthDay.java, djvm/src/main/java/sandbox/java/time/OffsetDateTime.java, djvm/src/main/java/sandbox/java/time/OffsetTime.java, djvm/src/main/java/sandbox/java/time/Period.java, djvm/src/main/java/sandbox/java/time/Year.java, djvm/src/main/java/sandbox/java/time/YearMonth.java, djvm/src/main/java/sandbox/java/time/ZoneId.java, djvm/src/main/java/sandbox/java/time/ZoneOffset.java, djvm/src/main/java/sandbox/java/time/ZonedDateTime.java, djvm/src/main/java/sandbox/java/time/zone/TzdbZoneRulesProvider.java, djvm/src/main/java/sandbox/java/time/zone/ZoneRulesException.java, djvm/src/main/java/sandbox/java/time/zone/ZoneRulesProvider.java, djvm/src/main/java/sandbox/java/util/Currency.java, djvm/src/main/kotlin/net/corda/djvm/analysis/AnalysisConfiguration.kt, djvm/src/main/kotlin/net/corda/djvm/analysis/JavaTimeConfiguration.kt, djvm/src/main/kotlin/net/corda/djvm/analysis/SewingKit.kt, djvm/src/main/kotlin/net/corda/djvm/rules/implementation/HandleExceptionUnwrapper.kt, djvm/src/main/kotlin/sandbox/java/lang/DJVM.kt, djvm/src/test/java/net/corda/djvm/execution/JavaTimeTest.java, djvm/src/test/kotlin/net/corda/djvm/TaskExecutor.kt, djvm/src/test/kotlin/net/corda/djvm/execution/SandboxExecutorTest.kt
Support `java.time.*` classes inside the sandbox. Mostly this involves teaching the DJVM how to convert instances between `java.time.X` and `sandbox.java.time.X`, but we also need to load the `tzdb.dat` file which contains Java's time zone database.
The majority of the work involves stitching `fromDJVM()` implementations into the `sandbox.java.time.X` classes, along with their accompanying bridge methods.
The `java.time.*` types are needed to deserialise Corda's `TimeWindow` object.
=> CORDA-2871: Add java.time.* types to those which can be marshalled into and out of sandbox.

djvm/src/main/java/sandbox/java/util/function/Supplier.java, djvm/src/main/kotlin/net/corda/djvm/analysis/AnalysisConfiguration.kt, djvm/src/main/kotlin/net/corda/djvm/execution/SandboxExecutor.kt, djvm/src/main/kotlin/net/corda/djvm/execution/SandboxRawExecutor.kt, djvm/src/main/kotlin/net/corda/djvm/rewiring/SandboxClassLoader.kt, djvm/src/main/kotlin/sandbox/TaskTypes.kt, djvm/src/main/kotlin/sandbox/java/lang/DJVM.kt, djvm/src/test/java/net/corda/djvm/execution/BasicInputOutputTest.java, djvm/src/test/kotlin/net/corda/djvm/TaskExecutor.kt, djvm/src/test/kotlin/net/corda/djvm/execution/SandboxExecutorTest.kt
Expose the `DJVM.sandbox(Object)` and `DJVM.unsandbox(Object)` functions via tasks `BasicInput` and `BasicOutput`.
=> CORDA-2871: Add built-in tasks to marshall basic objects into and out of the sandbox.

djvm/src/main/kotlin/net/corda/djvm/rewiring/SandboxClassLoader.kt, djvm/src/test/java/net/corda/djvm/execution/BasicInputOutputTest.java
Simplify Java generics by replacing `Function` with `UnaryOperator` for basic input/output tasks.
=> CORDA-2871: Use UnaryOperator for basic input/output tasks.

build.gradle
Ensure published POMs refer to the correct repository.
=> Upgrade DJVM repository URLs.

djvm/src/main/kotlin/net/corda/djvm/analysis/AnalysisConfiguration.kt, djvm/src/main/kotlin/net/corda/djvm/analysis/JavaPackageConfiguration.kt, djvm/src/main/kotlin/net/corda/djvm/code/EmitterModule.kt, djvm/src/main/kotlin/net/corda/djvm/rewiring/SandboxClassLoader.kt, djvm/src/main/kotlin/net/corda/djvm/rules/implementation/DisallowNonDeterministicMethods.kt, djvm/src/test/java/net/corda/djvm/execution/JavaPackageTest.java, djvm/src/test/java/net/corda/djvm/execution/JavaTimeTest.java, djvm/src/test/kotlin/net/corda/djvm/TaskExecutor.kt, djvm/src/test/kotlin/net/corda/djvm/execution/SandboxExecutorTest.kt
The `SandboxClassLoader` only expects a single thread of execution, but it can also be invoked from _outside_ the `sandbox.*` package space. It should therefore implement standard class loader locking, to be safe.
Sandbox classes can also reasonably be expected to support `Class.getPackage()`, although this could be dangerous inside the sandbox as it could potentially expose the `SandboxClassLoader` instance. For now, only support `Class.getPackage()` _outside_ the `sandbox.*` package space.
=> CORDA-2871: Enable Class.getPackage() for outside the sandbox.

djvm/build.gradle, djvm/src/main/java/sandbox/java/lang/System.java, djvm/src/main/java/sandbox/sun/util/calendar/ZoneInfoFile.java, djvm/src/main/kotlin/net/corda/djvm/analysis/AnalysisConfiguration.kt, djvm/src/main/kotlin/net/corda/djvm/analysis/JavaTimeConfiguration.kt, djvm/src/main/kotlin/net/corda/djvm/rules/implementation/DisallowNonDeterministicMethods.kt, djvm/src/test/java/net/corda/djvm/execution/JavaTimeTest.java
Configure the sandbox environment always to use the GMT / UTC time zone.
=> CORDA-2871: Set the default Java TimeZone to GMT.

djvm/build.gradle, djvm/src/main/java/sandbox/java/lang/Boolean.java, djvm/src/main/java/sandbox/java/lang/Byte.java, djvm/src/main/java/sandbox/java/lang/Character.java, djvm/src/main/java/sandbox/java/lang/Double.java, djvm/src/main/java/sandbox/java/lang/Float.java, djvm/src/main/java/sandbox/java/lang/Integer.java, djvm/src/main/java/sandbox/java/lang/Long.java, djvm/src/main/java/sandbox/java/lang/Number.java, djvm/src/main/java/sandbox/java/lang/Short.java, djvm/src/main/java/sandbox/java/util/Date.java, djvm/src/main/java/sandbox/java/util/concurrent/ConcurrentHashMap.java, djvm/src/main/java/sandbox/java/util/concurrent/atomic/AtomicInteger.java, djvm/src/main/java/sandbox/java/util/concurrent/atomic/AtomicLong.java, djvm/src/main/kotlin/net/corda/djvm/analysis/AnalysisConfiguration.kt, djvm/src/main/kotlin/net/corda/djvm/analysis/JavaTimeConfiguration.kt, djvm/src/main/kotlin/net/corda/djvm/rules/implementation/StaticConstantRemover.kt, djvm/src/main/kotlin/sandbox/java/lang/DJVM.kt, djvm/src/test/java/net/corda/djvm/execution/JavaTimeTest.java, djvm/src/test/java/net/corda/djvm/execution/SandboxExecutorJavaTest.java, djvm/src/test/java/net/corda/djvm/execution/SandboxThrowableJavaTest.java, djvm/src/test/kotlin/net/corda/djvm/TestBase.kt, djvm/src/test/kotlin/net/corda/djvm/rewiring/ClassRewriterTest.kt
- Stop templating the `Number` class to avoid possible infinite recursion in `toString()`.
- Add `Date` to the DJVM's list of native types.
- Fix loading of resource bundles, i.e. establish the bundle's parent chain.
- Ensure that `static final String` field values are interned.
- Remove some more cruft from `TestBase`.
=> CORDA-2871: Resolve issues blocking serialisation of ProtonJ primitives.

djvm/src/main/java/sandbox/java/util/ResourceBundle.java, djvm/src/main/kotlin/net/corda/djvm/analysis/AnalysisConfiguration.kt, djvm/src/main/kotlin/net/corda/djvm/analysis/JavaResourceBundleConfiguration.kt, djvm/src/main/kotlin/sandbox/java/lang/DJVM.kt, djvm/src/test/java/net/corda/djvm/execution/JavaTimeTest.java
- Migrate stitched ResourceBundle method configuration into a separate file.
- Stitch two extra methods to configure ResourceBundle objects more correctly.
=> CORDA-2871: Tidy up ResourceBundle handling.

djvm/src/main/java/sandbox/java/util/concurrent/atomic/AtomicReference.java, djvm/src/main/java/sandbox/java/util/function/BinaryOperator.java, djvm/src/main/java/sandbox/java/util/function/UnaryOperator.java, djvm/src/main/kotlin/net/corda/djvm/analysis/AnalysisConfiguration.kt
We need `AtomicReference` to support `Enumeration<*>.asSequence()` in Kotlin.
=> CORDA-2871: Support AtomicReference inside the sandbox.

djvm/src/main/kotlin/net/corda/djvm/execution/SandboxExecutor.kt, djvm/src/main/kotlin/net/corda/djvm/rewiring/SandboxClassLoader.kt, djvm/src/main/kotlin/net/corda/djvm/rewiring/SandboxClassLoadingException.kt, djvm/src/main/kotlin/net/corda/djvm/source/SourceClassLoader.kt, djvm/src/test/kotlin/net/corda/djvm/DJVMExceptionTest.kt, djvm/src/test/kotlin/net/corda/djvm/execution/KotlinNeedsKotlinTest.kt, djvm/src/test/kotlin/net/corda/djvm/execution/SandboxExecutorTest.kt, djvm/src/test/kotlin/net/corda/djvm/rewiring/ClassRewriterTest.kt, serialization/src/main/kotlin/net/corda/djvm/serialization/Serialization.kt
- Add a sensible top-level message to `SandboxClassLoadingException` so that the poor developers can tell what might be going wrong!
- Modify the deserialisation API so that we can specify both serialisation factory and serialisation context.
=> CORDA-2871: Sanity fixes!

djvm/src/main/kotlin/net/corda/djvm/rewiring/SandboxClassLoader.kt, djvm/src/test/kotlin/net/corda/djvm/DJVMExceptionTest.kt, djvm/src/test/kotlin/net/corda/djvm/execution/KotlinNeedsKotlinTest.kt, djvm/src/test/kotlin/net/corda/djvm/execution/SandboxExecutorTest.kt, djvm/src/test/kotlin/net/corda/djvm/rewiring/ClassRewriterTest.kt, serialization/src/test/kotlin/net/corda/djvm/serialization/DeserializeKotlinAliasTest.kt
ClassLoader.loadClass() needs to throw `ClassNotFoundException` for all cases where a class cannot be found. Throwing `SandboxClassLoadingException` in some cases is not good enough.
This fixes Kotlin's handling ot `typealias` inside the sandbox.
=> Ensure ClassLoader.loadClass() throws ClassNotFoundException.

djvm/src/main/kotlin/net/corda/djvm/rewiring/SandboxClassLoader.kt, djvm/src/main/kotlin/sandbox/java/lang/DJVM.kt, djvm/src/test/kotlin/net/corda/djvm/DJVMExceptionTest.kt
`SandboxClassWriter.getCommonSuperClass()` can throw `TypeNotPresentException` in some circumstances. Convert this into `ClassNotFoundException` to preserve behaviour of `ClassLoader.loadClass().`
=> CORDA-2871: Handle TypeNotPresentException

serialization/build.gradle, serialization/src/main/kotlin/net/corda/djvm/serialization/SandboxSerializerFactoryFactory.kt
Allow the DJVM to tell the Deserialiser which types are "primitive", and so should not be added to the object history.
=> CORDA-3218: Align DJVM with internal Corda Serialisation API.

djvm/src/main/kotlin/net/corda/djvm/analysis/AnalysisConfiguration.kt, djvm/src/main/kotlin/net/corda/djvm/code/Types.kt, djvm/src/main/kotlin/net/corda/djvm/rewiring/ThrowableWrapperFactory.kt
This is probably harmless, but is potentially confusing.
=> CORDA-2871: Stop accidentally loading DJVMException template into application classloader.

djvm-example/build.gradle, djvm-example/gradle.properties, djvm/src/main/kotlin/net/corda/djvm/analysis/AnalysisConfiguration.kt, djvm/src/main/kotlin/net/corda/djvm/execution/IsolatedTask.kt, djvm/src/main/kotlin/net/corda/djvm/rewiring/SandboxClassRemapper.kt, djvm/src/test/java/net/corda/djvm/execution/AnnotatedJavaClassTest.java, djvm/src/test/kotlin/net/corda/djvm/execution/AnnotatedKotlinClassTest.kt, gradle.properties
We cannot map any annotation that has an `Enum` method with a `default` value into the sandbox, because the JVM would try (and fail) to assign `Enum` to `sandbox.Enum` when asked to parse it.
The JPA annotations such as `@OneToMany` and `@ManyToMany` are examples of this, c.f. `FetchType`.
=> CORDA-3137: Only preserve annotations that we know we can handle.

djvm-example/build.gradle, djvm-example/src/test/kotlin/com/example/testing/TestBase.kt, djvm/src/main/kotlin/net/corda/djvm/analysis/AnalysisConfiguration.kt, djvm/src/test/java/net/corda/djvm/execution/AnnotatedJavaClassTest.java, djvm/src/test/java/net/corda/djvm/execution/SandboxExecutorJavaTest.java, djvm/src/test/java/net/corda/djvm/execution/SandboxThrowableJavaTest.java, djvm/src/test/kotlin/net/corda/djvm/TestBase.kt, djvm/src/test/kotlin/net/corda/djvm/execution/AnnotatedKotlinClassTest.kt, serialization/build.gradle, serialization/src/test/kotlin/net/corda/djvm/serialization/TestBase.kt
Not every annotation needs to be stitched back into the unsandboxed package space. Allow us to configure the sandbox to accept globs of "safe" annotation classes. By "safe", I mean ones that do not have any `Enum` values.
=> CORDA-3137: Allow the sandbox to handle annotations that match given patterns.

djvm/src/main/java/sandbox/java/lang/DJVMThrowableWrapper.java, djvm/src/main/kotlin/net/corda/djvm/analysis/AnalysisConfiguration.kt, djvm/src/main/kotlin/net/corda/djvm/analysis/ClassAndMemberVisitor.kt, djvm/src/main/kotlin/net/corda/djvm/analysis/ClassResolver.kt, djvm/src/main/kotlin/net/corda/djvm/analysis/ExceptionResolver.kt, djvm/src/main/kotlin/net/corda/djvm/analysis/Whitelist.kt, djvm/src/main/kotlin/net/corda/djvm/rewiring/SandboxClassLoader.kt, djvm/src/main/kotlin/net/corda/djvm/rewiring/SandboxClassRemapper.kt, djvm/src/main/kotlin/net/corda/djvm/rewiring/SandboxRemapper.kt, djvm/src/main/kotlin/net/corda/djvm/rules/implementation/DisallowNonDeterministicMethods.kt, djvm/src/main/kotlin/net/corda/djvm/rules/implementation/StubOutReflectionMethods.kt, djvm/src/main/kotlin/sandbox/java/lang/DJVM.kt, djvm/src/test/java/net/corda/djvm/Utilities.java, djvm/src/test/java/net/corda/djvm/execution/MaliciousClassLoaderTest.java, djvm/src/test/java/net/corda/djvm/execution/SandboxExecutorJavaTest.java, djvm/src/test/java/net/corda/djvm/execution/SandboxThrowableJavaTest.java, djvm/src/test/kotlin/net/corda/djvm/TestBase.kt, djvm/src/test/kotlin/net/corda/djvm/analysis/ClassResolverTest.kt, djvm/src/test/kotlin/net/corda/djvm/execution/SandboxExecutorTest.kt, djvm/src/test/kotlin/net/corda/djvm/source/SourceClassLoaderTest.kt
Pinned classes are a concept left over from the early days of the DJVM. They were only being used in a few tests, and we can replace these use-cases by extending the tests' whitelist instead.
Delete all reference to pinned classes from the DJVM, _ad good riddance!_
=> CORDA-2871: Remove pinned classes from AnalysisConfiguration.

build.gradle, djvm/build.gradle
- Enable the G1 garbage collector.
- Disable JIT compilation for all `sandbox.*` classes because the effort is always wasted.
=> Update JVM options for testing.

djvm/src/main/kotlin/net/corda/djvm/analysis/AnalysisConfiguration.kt, djvm/src/main/kotlin/net/corda/djvm/execution/SandboxExecutor.kt, djvm/src/main/kotlin/net/corda/djvm/execution/SandboxRawExecutor.kt, djvm/src/main/kotlin/net/corda/djvm/rewiring/SandboxClassLoader.kt, djvm/src/main/kotlin/net/corda/djvm/rules/implementation/DisallowDynamicInvocation.kt, djvm/src/main/kotlin/net/corda/djvm/source/SourceClassLoader.kt, djvm/src/main/kotlin/sandbox/java/lang/DJVM.kt, djvm/src/test/kotlin/net/corda/djvm/TestBase.kt, djvm/src/test/kotlin/net/corda/djvm/execution/SandboxExecutorTest.kt, djvm/src/test/kotlin/net/corda/djvm/rewiring/ClassRewriterTest.kt
- Remove unnecessary references to `sun.*` classes.
- Replace `Class.newInstance()` with `Class.getDeclaredConstructor().newInstance()`.
- Use `Type` class from external ASM library instead of JDK's internal one.
=> Fix some simple compiler warnings and errors with Java 11.

djvm-example/src/test/kotlin/com/example/testing/TestBase.kt, djvm/src/main/kotlin/net/corda/djvm/SandboxConfiguration.kt, djvm/src/main/kotlin/net/corda/djvm/analysis/AnalysisConfiguration.kt, djvm/src/test/kotlin/net/corda/djvm/TestBase.kt, djvm/src/test/kotlin/net/corda/djvm/rewiring/ByteCodeCacheTest.kt, serialization/src/test/kotlin/net/corda/djvm/serialization/TestBase.kt
Uncouple the `SandboxConfiguration` object from the `AnalysisConfiguration` object when creating a child sandbox by using a `Consumer` function.
=> CORDA-2877: Refactor how we create child SandboxConfiguration objects.

djvm/src/main/java/sandbox/java/lang/String.java, djvm/src/main/kotlin/net/corda/djvm/analysis/AnalysisConfiguration.kt, djvm/src/main/kotlin/net/corda/djvm/code/EmitterModule.kt, djvm/src/main/kotlin/net/corda/djvm/rewiring/SandboxClassLoader.kt, djvm/src/main/kotlin/net/corda/djvm/rewiring/SandboxClassWriter.kt, djvm/src/main/kotlin/net/corda/djvm/source/ClassHeader.kt, djvm/src/main/kotlin/net/corda/djvm/source/SourceClassLoader.kt, djvm/src/test/kotlin/net/corda/djvm/source/SourceClassLoaderTest.kt
- Update `sandbox.java.lang.String` to be compatible with Java 11.
- Rewrite `SourceClassLoader` to load `ClassHeader` instead of `Class` for sake of ASM's "common superclass" algorithm.
The "common superclass" algorithm needs to be able to load `java.*` byte-code from `deterministic-rt.jar` in order to determine whether `A` is assignable to `B`. This means that we _*cannot*_ load `Class` instances because a Java `ClassLoader` refuses to create new classes for the `java.*` package space. (Only the bootstrap classloader can do that.) So I've created `ClassHeader` as a bare-bones replacement for `Class` that is _just_ enough for ASM's "common superclass" algorithm to use instead.
This should also effectively fix #27, although some of the DJVM's unit tests will still fail due to their …
=> CORDA-3286: Update the DJVM to run on Java 11,

djvm/src/main/kotlin/net/corda/djvm/source/ClassHeader.kt, djvm/src/test/kotlin/net/corda/djvm/source/SourceClassLoaderTest.kt
There are four cases to consider for `class1.isAssignableFrom(class2)`:
- `class1`, `class2` are both classes: `class1.internalName` must match either `class2.internalName` or the `internalName` for any of `class2`'s superclasses.
- `class1` is a class and `class2` is an interface: This can never succeed.
- `class1` is an interface and `class2` is a class: `class1.internalName` must match either the `internalName`  for any of `class2`'s interfaces, any interface implemented by one of `class2`'s superclasses, or any superinterface of any of these interfaces.
- `class1`, `class2` are both interfaces: `class1.internalName` must match either `class2.internalName`, the `internalName` for any of `class2`'s interfaces, or any of their superinterfaces.
We need to cover all of these cases and …
=> CORDA-3286: Detect when a superclass can be assigned to an interface.

djvm-example/src/test/kotlin/com/example/testing/TestBase.kt, djvm/src/main/kotlin/net/corda/djvm/execution/ExecutionProfile.kt, serialization/src/test/kotlin/net/corda/djvm/serialization/TestBase.kt
Reimplement `ExecutionProfile` as an immutable data class instead of an enum. This allows DJVM clients (i.e. the Corda Node) to create a tuned profile rather than relying on a limited set of predefined ones.
=> CORDA-3292: Reimplement ExecutionProfile as an immutable data class.

serialization/src/test/kotlin/net/corda/djvm/serialization/DeserializeCertificatesTest.kt
The sandbox uses UNIX line endings, and so the host JVM's output needs to be converted to match before the tests compare them. Fix this conversion step which was failing for the Certificates tests.
=> Fix tests broken by Windows line endings.

djvm/src/main/kotlin/net/corda/djvm/analysis/AnalysisConfiguration.kt, djvm/src/main/kotlin/net/corda/djvm/code/EmitterModule.kt, djvm/src/main/kotlin/net/corda/djvm/rules/implementation/StubOutReflectionMethods.kt, djvm/src/main/kotlin/sandbox/java/lang/DJVM.kt, djvm/src/test/kotlin/com/example/testing/HasBrokenConstructor.kt, djvm/src/test/kotlin/com/example/testing/HasProtectedConstructor.kt, djvm/src/test/kotlin/com/example/testing/HasUserExceptionConstructor.kt, djvm/src/test/kotlin/com/example/testing/ImpossibleInstance.kt, djvm/src/test/kotlin/net/corda/djvm/execution/BasicCryptoTest.kt, djvm/src/test/kotlin/net/corda/djvm/execution/ExpectedException.kt, djvm/src/test/kotlin/net/corda/djvm/execution/NewInstanceFailureTest.kt
- Do not stub out methods on java.lang.reflect.* exception classes.
- Similarly for java.lang.invoke.* exceptions too.
- Also handle exception constructor with args (Throwable, String).
=> More robust handling for exceptions thrown by Constructor.newInstance().

djvm-example/src/test/kotlin/com/example/testing/TestBase.kt, djvm/src/main/kotlin/net/corda/djvm/execution/IsolatedTask.kt, djvm/src/test/kotlin/net/corda/djvm/TestBase.kt, serialization/src/test/kotlin/net/corda/djvm/serialization/TestBase.kt
Install an `UncaughtExceptionHandler` for each DJVM task thread so that any exceptions from (say) creating the `SandboxClassLoader` are not lost.
Avian _does_ support `Thread.UncaughtExceptionHandler` :wink:.
=> CORDA-3309: Install UncaughtExceptionHandler for DJVM tasks.

djvm-example/src/test/kotlin/com/example/testing/TestBase.kt, djvm/src/main/kotlin/net/corda/djvm/execution/IsolatedTask.kt, djvm/src/test/kotlin/net/corda/djvm/TestBase.kt, serialization/src/test/kotlin/net/corda/djvm/serialization/TestBase.kt
Use `UncaughtExceptionHandler` to catch _all_ task exceptions. This should make the exception-handling logic simpler. by removing some "magic" from `IsolatedTask` concerning "provisional" `SandboxClassLoader` errors,
=> CORDA-3309; Remove explicit try-catch in favour of UncaughtExceptionHandler.

djvm/src/main/kotlin/net/corda/djvm/analysis/ClassAndMemberVisitor.kt, djvm/src/main/kotlin/net/corda/djvm/analysis/SewingKit.kt, djvm/src/main/kotlin/net/corda/djvm/analysis/SourceLocation.kt, djvm/src/main/kotlin/net/corda/djvm/code/ClassMutator.kt, djvm/src/main/kotlin/net/corda/djvm/code/instructions/MemberAccessInstruction.kt, djvm/src/main/kotlin/net/corda/djvm/execution/CostSummary.kt, djvm/src/main/kotlin/net/corda/djvm/execution/ExecutionSummary.kt, djvm/src/main/kotlin/net/corda/djvm/execution/ExecutionSummaryWithResult.kt, djvm/src/main/kotlin/net/corda/djvm/messages/Message.kt, djvm/src/main/kotlin/net/corda/djvm/messages/MessageCollection.kt, djvm/src/main/kotlin/net/corda/djvm/rewiring/SandboxClassLoadingException.kt, djvm/src/main/kotlin/net/corda/djvm/source/SourceClassLoader.kt, djvm/src/main/kotlin/net/corda/djvm/utilities/Processor.kt, djvm/src/main/kotlin/net/corda/djvm/validation/RuleValidator.kt, djvm/src/test/kotlin/net/corda/djvm/analysis/SourceLocationTest.kt, djvm/src/test/kotlin/net/corda/djvm/code/ClassMutatorTest.kt, djvm/src/test/kotlin/net/corda/djvm/code/EmitterModuleTest.kt
Adding default parameters to constructors in Kotlin has non-obvious implications for the ABI, i.e. the constructor signatures have `ILkotlin/jvm/internal/DefaultConstructorMarker;` silently appended to their arguments. This complicates extending these classes later in a backwards-compatible way.
Remove as many default parameters from as many constructors as possible before we release v1.0.
=> Make API more Java-friendly by removing constructor default parameters.

djvm/build.gradle, djvm/src/main/java/sandbox/java/util/Collections.java, djvm/src/main/java/sandbox/java/util/Properties.java, djvm/src/main/java/sandbox/java/util/ServiceLoader.java, djvm/src/main/kotlin/net/corda/djvm/analysis/AnalysisConfiguration.kt, djvm/src/main/kotlin/net/corda/djvm/analysis/JavaCalendarConfiguration.kt, djvm/src/main/kotlin/sandbox/java/lang/DJVM.kt, djvm/src/test/java/net/corda/djvm/execution/JavaChronologyTest.java
Reimplement `sun.util.calendar.CalendarSystem.getCalendarProperties()` to fetch the `calendars.properties` file from the DJVM's system resources.
This allows us to instantiate the JVM's built-in `Chronology` objects.
=> Add calendars.properties to the DJVM.

djvm/src/main/kotlin/sandbox/java/lang/DJVM.kt
The exceptions inside `ExceptionInInitializerError` and `InvocationTargetException` are both allowed to be `null`, so disable Kotlin's null-check when marshalling instances out of the sandbox.
=> Tolerate exceptions inside ExceptionInInitializerError and InvocationTargetException being null.

build.gradle, djvm/build.gradle, djvm/src/main/java/net/corda/djvm/CordaInternal.java, djvm/src/main/kotlin/net/corda/djvm/analysis/SewingKit.kt, gradle.properties, settings.gradle
Use the API Scanner plugin to summarise the DJVM's public API. This should make it easier to find unwanted Kotlin-speoific elements, such as constructors with default parameter values.
=> CORDA-3377: Add the API Scanner plugin.

djvm/src/main/kotlin/net/corda/djvm/analysis/AnalysisConfiguration.kt, djvm/src/main/kotlin/net/corda/djvm/code/EmitterModule.kt, djvm/src/main/kotlin/net/corda/djvm/rewiring/ClassRewriter.kt, djvm/src/test/java/net/corda/djvm/rewiring/StitchedInterfaceTest.java
Hotspot doesn't seem to mind that the generic signature is incorrect so long as the super-interface is still added.  However, the generated byte-code is still incorrect regardless.
=> CORDA-3380: Update the class signature when stitching generic interfaces.

build.gradle
TeamCity uses environment variables for Artifactory credentials, but users may prefer other methods.
=> Allow users' Artifactory credentials to be stored locally.

djvm/src/main/kotlin/net/corda/djvm/SandboxRuntimeContext.kt, djvm/src/main/kotlin/net/corda/djvm/execution/SandboxExecutor.kt, djvm/src/main/kotlin/net/corda/djvm/messages/MessageCollection.kt, djvm/src/main/kotlin/net/corda/djvm/rewiring/SandboxClassLoader.kt, djvm/src/main/kotlin/net/corda/djvm/source/SourceClassLoader.kt
Provisional error messages were a workaround for `SandboxClassLoader` aborting loading a new class when it failed to find that class in the very first `SourceClassLoader` it searched.
Both `SandboxClassLoader` and `SourceClassLoader` have since evolved, making provisional error messages obsolete.
=> Refactor how SandboxClassLoader fetches source byte-code.

djvm/src/main/kotlin/net/corda/djvm/code/ClassMutator.kt, djvm/src/main/kotlin/net/corda/djvm/costing/RuntimeCost.kt, djvm/src/main/kotlin/net/corda/djvm/costing/RuntimeCostSummary.kt, djvm/src/main/kotlin/net/corda/djvm/costing/TypedRuntimeCost.kt, djvm/src/main/kotlin/net/corda/djvm/execution/QueueProcessor.kt, djvm/src/main/kotlin/net/corda/djvm/execution/SandboxExecutor.kt, djvm/src/main/kotlin/net/corda/djvm/rewiring/SandboxClassLoader.kt, djvm/src/main/kotlin/net/corda/djvm/utilities/Processor.kt, djvm/src/main/kotlin/net/corda/djvm/validation/RuleValidator.kt, djvm/src/main/kotlin/sandbox/RuntimeCostAccounter.kt, djvm/src/test/kotlin/net/corda/djvm/costing/RuntimeCostTest.kt, settings.gradle
Replace Kotlin function references with Java functional interfaces.
Remove superfluous properties.
Resolve some minor compiler warnings.
=> CORDA-3377: Remove more Kotlinisms from the DJVM's API

djvm-example/src/test/kotlin/com/example/testing/TestBase.kt, djvm/src/main/kotlin/net/corda/djvm/SandboxConfiguration.kt, djvm/src/main/kotlin/net/corda/djvm/SandboxRuntimeContext.kt, djvm/src/main/kotlin/net/corda/djvm/execution/IsolatedTask.kt, djvm/src/main/kotlin/net/corda/djvm/execution/SandboxExecutor.kt, djvm/src/main/kotlin/net/corda/djvm/execution/SandboxRawExecutor.kt, djvm/src/test/kotlin/net/corda/djvm/SandboxConfigurationTest.kt, djvm/src/test/kotlin/net/corda/djvm/TestBase.kt
- Replace more Kotlin function references with `Consumer` and `Function`
- Remove unused `IsolatedTask.classLoader` property.
=> CORDA-3377: Remove even more Kotlinisms from DJVM API.

deterministic-rt/.gitignore, deterministic-rt/Makefile, deterministic-rt/build.gradle, deterministic-rt/gradle.properties, deterministic-rt/settings.gradle
commit c86483091efa19924363d7b571450f389e35db37
Author: Chris Rankin <chris.rankin@r3.com>
Date:   Mon Nov 18 14:28:02 2019 +0000
CORDA-2963: Move deterministic-rt files into their own subdirectory.
commit 148f0358e1ac80273e2474843bf9e6fbf760f4cb
Author: Chris Rankin <chris.rankin@r3.com>
Date:   Mon Nov 18 13:54:51 2019 +0000
CORDA-2963: Add calendars.properties to deterministic-rt.jar. (#5730)
commit 8be3e65e5170c5ce4fbe8da758b61cf2ccc4eaa8
Author: Chris Rankin <chris.rankin@r3.com>
Date:   Fri Oct 25 10:39:56 2019 +0100
CORDA-2963: Update the Deterministic Java API artifacts. (#5637)
* CORDA-2963: Restore FileChannel to deterministic-rt but still remove it from the API artifact.
* CORDA-2963: Restore stub ObjectStream classes to deterministic-rt but still remove them from the API …
=> CORDA-2963: Migrate create-jdk8 module from Corda into deterministic-rt.

deterministic-rt/build.gradle
Ensure that we publish the deterministic-rt artifacts under the correct GPLv2+CE licence.
=> CORDA-2963: Add GPLv2+CE licence to deterministic-rt POM artifact.

djvm-example/build.gradle, djvm-example/gradle.properties, djvm/build.gradle, gradle.properties
It's time to stop using a SNAPSHOT version of deterministic-rt.jar. The first release candidate of this artifact has now been published to the corda-dependencies repository in Artifactory.
=> CORDA-2963: Update to use first release candidate for deterministic-rt.

deterministic-rt/Makefile, deterministic-rt/build.gradle
We need the deterministic-rt artifacts to be repeatable, so ensure that we build them from a known tag in our OpenJDK repository.
=> CORDA-2963: Update deterministic-rt module to build from a tag.

deterministic-rt/build.gradle
Remove file timestamps from within the jar so that the artifact can be recreated exactly.
=> CORDA-2963: Ensure that deterministic-rt.jar artifact build is repeatable.

djvm-example/build.gradle, djvm-example/gradle.properties, djvm-example/src/main/scala/com/example/testing/BadScalaTask.scala, djvm-example/src/main/scala/com/example/testing/ScalaTask.scala, djvm-example/src/test/java/com/example/testing/JavaSandboxTest.java, djvm-example/src/test/kotlin/com/example/testing/KotlinSandboxTest.kt, djvm-example/src/test/kotlin/com/example/testing/ScalaSandboxTest.kt, djvm-example/src/test/kotlin/com/example/testing/TestBase.kt, djvm/build.gradle, djvm/src/test/java/net/corda/djvm/execution/CapturingLambdaTest.java, djvm/src/test/kotlin/net/corda/djvm/TestBase.kt
Add some test cases to explore how Scala behaves inside the sandbox - even if the answer is "Badly!".
=> Extend DJVM example project to include Scala support.

djvm/src/main/kotlin/net/corda/djvm/rewiring/SandboxClassLoader.kt
The DJVM code is very likely inside the system classloader, but use the DJVM's own classloader explicitly as the sandbox's parent classloader.
=> CORDA-3377: Use DJVM's own ClassLoader as the base ClassLoader of every sandbox.

build.gradle, deterministic-rt/build.gradle, djvm-example/build.gradle
The DJVM artifacts are now hosted in Artifactory's corda-dependencies and corda-dependencies-dev repositories.
=> NOTICK: Publish SNAPSHOT builds to corda-dependencies-dev repository.

djvm-example/src/test/kotlin/com/example/testing/TestBase.kt, djvm/cli/src/main/kotlin/net/corda/djvm/tools/cli/ClassCommand.kt, djvm/src/main/kotlin/net/corda/djvm/SandboxConfiguration.kt, djvm/src/main/kotlin/net/corda/djvm/SandboxRuntimeContext.kt, djvm/src/test/kotlin/net/corda/djvm/TestBase.kt
The `enableTracing` parameter is superfluous and can be replaced by a null `ExecutionProfile`.
=> CORDA-3377: Remove explicit enableTracing option from SandboxConfiguration.

djvm/src/main/kotlin/net/corda/djvm/rewiring/SandboxClassLoader.kt
This has been replaced by `SandboxClassLoader.createSandboxFunction()`.
=> CORDA-3377: Remove deprecated createTaskFactory() function.

djvm/src/main/java/sandbox/java/time/zone/ZoneRulesProvider.java, djvm/src/main/kotlin/net/corda/djvm/code/EmitterModule.kt, djvm/src/main/kotlin/net/corda/djvm/rewiring/SandboxClassLoader.kt, djvm/src/main/kotlin/net/corda/djvm/rules/implementation/DisallowCatchingBlacklistedExceptions.kt, djvm/src/main/kotlin/sandbox/RuntimeCostAccounter.kt, djvm/src/main/kotlin/sandbox/TaskTypes.kt, djvm/src/main/kotlin/sandbox/java/lang/DJVM.kt, djvm/src/test/java/net/corda/djvm/execution/BasicInputOutputTest.java, djvm/src/test/java/net/corda/djvm/execution/ImportTaskJavaTest.java, djvm/src/test/kotlin/net/corda/djvm/execution/ImportTaskTest.kt
Fix some wrinkles with the `SandboxClassLoader.createForImport()` API:
- Make it more forgiving of Kotlin's non-nullable generic types.
- Handle exceptions thrown by an imported tasks to guarantee that sandboxed code can catch them.
Also improve test coverage for imported tasks, and fix missing `intern` for a constant String value.
=> CORDA-3377: Marshall exceptions into the sandbox from imported Functions.

djvm-example/src/test/java/com/example/testing/JavaSandboxTest.java, djvm-example/src/test/kotlin/com/example/testing/TestBase.kt, djvm/src/test/java/net/corda/djvm/execution/AnnotatedJavaClassTest.java, djvm/src/test/java/net/corda/djvm/execution/Base64Test.java, djvm/src/test/java/net/corda/djvm/execution/BasicInputOutputTest.java, djvm/src/test/java/net/corda/djvm/execution/BitSetTest.java, djvm/src/test/java/net/corda/djvm/execution/CapturingLambdaTest.java, djvm/src/test/java/net/corda/djvm/execution/DataInputStreamTest.java, djvm/src/test/java/net/corda/djvm/execution/DatatypeConverterTest.java, djvm/src/test/java/net/corda/djvm/execution/ImportTaskJavaTest.java, djvm/src/test/java/net/corda/djvm/execution/JarInputStreamTest.java, djvm/src/test/java/net/corda/djvm/execution/JavaChronologyTest.java, djvm/src/test/java/net/corda/djvm/execution/JavaPackageTest.java, djvm/src/test/java/net/corda/djvm/execution/JavaTimeTest.java, djvm/src/test/java/net/corda/djvm/execution/JavaUUIDTest.java, djvm/src/test/java/net/corda/djvm/execution/MaliciousClassLoaderTest.java, djvm/src/test/java/net/corda/djvm/execution/MaliciousClassTest.java, djvm/src/test/java/net/corda/djvm/execution/SandboxCloneableTest.java, djvm/src/test/java/net/corda/djvm/execution/SandboxConcurrentHashMapTest.java, djvm/src/test/java/net/corda/djvm/execution/SandboxCurrencyTest.java, djvm/src/test/java/net/corda/djvm/execution/SandboxEnumJavaTest.java, djvm/src/test/java/net/corda/djvm/execution/SandboxExecutorJavaTest.java, djvm/src/test/java/net/corda/djvm/execution/SandboxObjectHashCodeJavaTest.java, djvm/src/test/java/net/corda/djvm/execution/SandboxStrictMathTest.java, djvm/src/test/java/net/corda/djvm/execution/SandboxStringTest.java, djvm/src/test/java/net/corda/djvm/execution/SandboxThrowableJavaTest.java, djvm/src/test/java/net/corda/djvm/execution/SecurityManagerTest.java, djvm/src/test/java/net/corda/djvm/execution/X500Tests.java, djvm/src/test/java/net/corda/djvm/rewiring/StitchedInterfaceTest.java, djvm/src/test/kotlin/net/corda/djvm/TestBase.kt
We shouldn't need to terminate every `SandboxRuntimeContext` lambda with
```java
return null;
```
when writing tests in Java.
=> CORDA-3377: Update TestBase classes to make writing Java tests more natural.

djvm/src/main/java/sandbox/java/util/function/Predicate.java, djvm/src/main/kotlin/net/corda/djvm/analysis/AnalysisConfiguration.kt, djvm/src/main/kotlin/net/corda/djvm/rewiring/Predicates.kt, djvm/src/main/kotlin/sandbox/TaskTypes.kt, djvm/src/test/java/net/corda/djvm/execution/EmptyEnum.java, djvm/src/test/java/net/corda/djvm/execution/JavaSandboxPredicateTest.java, djvm/src/test/kotlin/net/corda/djvm/execution/SandboxExecutorTest.kt, djvm/src/test/kotlin/net/corda/djvm/execution/SandboxPredicateTest.kt
While `java.util.function.Function<T,R>` is fine for passing objects into and out of the sandbox, it is not ideal for handling primitive Java types such as `boolean`, `int` or `long` which require no marshalling at all.
Create a new task for executing `Predicate<T>` functions without using reflection.
=> CORDA-3536: Add support for exposing Predicate<?> tasks.

djvm/src/main/java/sandbox/java/lang/DJVMException.java, djvm/src/main/kotlin/net/corda/djvm/rules/Rule.kt, djvm/src/test/java/net/corda/djvm/Action.java, djvm/src/test/kotlin/foo/bar/sandbox/Callable.kt, djvm/src/test/kotlin/sandbox/greymalkin/StringReturner.kt
Add the `@FunctionalInterface` annotation to appropriate interfaces, mainly for documentation purposes.
=> CORDA-3377: Annotate interfaces as @FunctionalInterface.

djvm/src/main/kotlin/net/corda/djvm/analysis/AnalysisConfiguration.kt, djvm/src/main/kotlin/net/corda/djvm/rewiring/SandboxClassRemapper.kt, djvm/src/test/java/net/corda/djvm/execution/AnnotatedJavaClassTest.java
The `java.lang.FnctionalInterface` annotation has no methods and is therefore "safe". It also has "runtime" visibility and so should be discoverable. Therefore preserve this annotation inside the sandbox. Preserve the original annotation too in order to maintain the contract with the Java language.
=> CORDA-3377: Preserve the `@FunctionalInterface` annotation because it is safe.

djvm/src/main/kotlin/net/corda/djvm/analysis/AnalysisConfiguration.kt, djvm/src/main/kotlin/net/corda/djvm/analysis/Whitelist.kt, djvm/src/main/kotlin/net/corda/djvm/rewiring/SewingKit.kt, djvm/src/test/java/net/corda/djvm/JavaAnnotation.java, djvm/src/test/java/net/corda/djvm/JavaLabel.java, djvm/src/test/java/net/corda/djvm/JavaLabels.java, djvm/src/test/java/net/corda/djvm/execution/AnnotatedJavaClassTest.java, djvm/src/test/kotlin/net/corda/djvm/KotlinLabel.kt, djvm/src/test/kotlin/net/corda/djvm/analysis/WhitelistTest.kt, djvm/src/test/kotlin/net/corda/djvm/execution/AnnotatedKotlinClassTest.kt
Kotlin reflection and Corda need to be able to examine the annotations on sandbox classes, which means that the unsandboxed values of _some_ annotations need to be preserved. We have also
whitelisted Java's `@Repeatable` annotation, which means that we _do_ need to be able to "stitch back" the unsandboxed values of annotations that have annotation-typed parameters.
The plan here is:
- Whitelist safe (i.e. ones without `Enum` fields) fundamental Java 8 annotations, and preserve them on sandboxed classes.
- Preserve safe fundamental Kotlin annotations by stitching the unsandboxed values underneath the sandboxed ones. Note that we _never_ whitelist Kotlin classes - see `SandboxClassRemapper.visitAnnotation()`, which updates the data in the`@kotlin.Metadata` annotations by just transforming …
=> CORDA-3377: Preserve basic Java and Kotlin annotations inside the sandbox.

djvm/src/main/kotlin/net/corda/djvm/analysis/AnalysisContext.kt, djvm/src/main/kotlin/net/corda/djvm/references/ReferenceMap.kt, djvm/src/main/kotlin/net/corda/djvm/rewiring/SandboxClassLoader.kt, djvm/src/main/kotlin/net/corda/djvm/source/SourceClassLoader.kt, djvm/src/test/kotlin/net/corda/djvm/ExceptionWithoutSyntheticCounterpartTest.kt, djvm/src/test/kotlin/net/corda/djvm/SyntheticExceptionTest.kt
- Fix a directory descriptor leak in SourceClassLoader.
- Simplify how SandboxClassLoader resolves new classes.
- Remove an unused constructor parameter from ReferenceMap.
- Add some more test cases for loading Throwable classes.
=> Small fixes before releasing 1.0

djvm/src/test/kotlin/net/corda/djvm/ExceptionWithoutSyntheticCounterpartTest.kt, djvm/src/test/kotlin/net/corda/djvm/SyntheticExceptionCachingTest.kt, djvm/src/test/kotlin/net/corda/djvm/SyntheticExceptionTest.kt, djvm/src/test/kotlin/net/corda/djvm/TestBase.kt, djvm/src/test/kotlin/net/corda/djvm/execution/ExternalByteCodeCacheTest.kt, djvm/src/test/kotlin/net/corda/djvm/rewiring/ByteCodeCacheAccess.kt
Extend test coverage to ensure that `Throwable` wrapper classes are cached correctly.
We don't add synthetic `Throwable` wrapper classes to the external cache because they are small and cheap to create. Make this behaviour clear in the unit tests too.
=> CORDA-3377: Extend test coverage for synthetic exception classes.

README.md, djvm/src/main/kotlin/net/corda/djvm/rewiring/SandboxClassLoader.kt, djvm/src/main/kotlin/net/corda/djvm/source/SourceClassLoader.kt, djvm/src/main/kotlin/net/corda/djvm/utilities/Logging.kt, djvm/src/test/kotlin/net/corda/djvm/execution/ExternalByteCodeCacheTest.kt
Use `String.intern()` on `URL.toString()` values when creating `ByteCodeKey` objects. This will ensure that the keys will use exactly one instance of `String` per unique URL value.
=> CORDA-3642: Reduce memory footprint of external byte-code cache.

djvm/src/main/kotlin/sandbox/java/lang/DJVM.kt
System resources are supposed to be loaded from the system ClassLoader. Note that `ClassLoader.getResource()` always delegates to its parent ClassLoader first, if it has one.
=> Use DJVM systemClassLoader property consistently.

djvm/src/main/java/sandbox/java/lang/ExceptionInInitializerError.java, djvm/src/main/kotlin/sandbox/java/lang/DJVM.kt, djvm/src/test/kotlin/net/corda/djvm/JVMExceptionTest.kt
Ensure that `InvocationTargetException`, `ExceptionInInitializerError` and `ClassNotFoundException` can be marshalled out of the sandbox when explicitly thrown. They are usually thrown by the JVM itself, but there's nothing to stop users doing it too.
=> CORDA-3649: Improve marshalling of some exceptions out of the sandbox.

djvm/src/main/java/sandbox/java/io/DJVMInputStream.java, djvm/src/main/java/sandbox/java/util/concurrent/atomic/DJVM.java, djvm/src/main/java/sandbox/java/util/concurrent/locks/DJVMConditionObject.java, djvm/src/main/java/sandbox/javax/security/auth/x500/DJVM.java
Ensure that the private DJVM helper classes are `final`.
=> Lock down the DJVM internal classes.

djvm/src/main/java/sandbox/java/lang/Object.java, djvm/src/test/kotlin/net/corda/djvm/DJVMTest.kt
Extend array test cases to include `null` values.
=> CORDA-3684: Fix NPE when unsandboxing an array that contains null.

djvm/src/main/java/sandbox/sun/security/action/GetPropertyAction.java
Provide values for the following system properties:
- `user.language`
- `path.separator`
This just makes the settings explicit; there is no change in behaviour.
=> Initialise the DJVM with more standard system properties.

djvm/src/main/kotlin/net/corda/djvm/rewiring/SandboxClassLoader.kt, djvm/src/main/kotlin/sandbox/java/lang/DJVM.kt, djvm/src/test/java/net/corda/djvm/execution/JavaObjectArraysTest.java, djvm/src/test/java/net/corda/djvm/execution/JavaPrimitiveArraysTest.java
Fix the type-mapping logic when marshalling objects both into and out of the sandbox at runtime. Use the `ClassResolver` so that we can consult the whitelist of types that do not need mapping, e.g. `java.io.Serializable` and `java.lang.Cloneable`.
=> CORDA-3713: Marshall multi-dimensional arrays with the correct component types.

djvm/src/main/kotlin/net/corda/djvm/rewiring/SandboxClassLoader.kt
Implement
```kotlin
protected fun SandboxClassLoader.findClass(String): Class<*>
```
so that new JDK9+ API
```kotlin
protected fun SandboxClassLoader.findClass(String, String): Class<*>
```
has the correct behaviour.
=> CORDA-3743: Implement SandboxClassLoader.findClass(String) for sake of JDK >= 9.

djvm-example/src/test/java/com/example/testing/JavaSandboxTest.java, djvm/src/main/java/sandbox/java/lang/System.java, djvm/src/test/java/net/corda/djvm/execution/AnnotationProxyJavaTest.java, djvm/src/test/java/net/corda/djvm/execution/MaliciousClassLoaderTest.java, djvm/src/test/kotlin/net/corda/djvm/execution/SandboxExecutorTest.kt
Add stubs for `java.lang.System.currentTimeMillis()` and `java.lang.System.nanoTime()` to the DJVM's template code so that these two functions result in `RuleViolationError` exceptions rather than `NoSuchMethodException`.
=> CORDA-3748: Add error stubs for System.currentTimeMillis() and System.nanoTime().

djvm/src/main/kotlin/net/corda/djvm/rules/implementation/DisallowUnsupportedApiVersions.kt
Byte-code v1.2 chosen as the new lower bound because this is the first version that supports `strictfp`.
=> CORDA-3749: Allow DJVM to accept Java byte-code versions v1.2 - v1.8.

compiler-control.txt, djvm/build.gradle
Disable the JVM's C2 compiler for all `sandbox.*` classes when building on Java 11.
=> Add JVM compiler directives for testing on JDK11 JVM.

djvm/src/main/kotlin/net/corda/djvm/analysis/AnalysisConfiguration.kt, djvm/src/main/kotlin/net/corda/djvm/analysis/ClassResolver.kt, djvm/src/main/kotlin/net/corda/djvm/rewiring/SandboxClassLoader.kt, djvm/src/main/kotlin/net/corda/djvm/rewiring/SandboxClassRemapper.kt, djvm/src/main/kotlin/net/corda/djvm/validation/RuleContext.kt
The logic for mapping class names into and out of the sandbox belongs in `ClassResolver`. Remove the logic which had "leaked" into `AnalysisConfiguration` to make `ClassResolver` the Source of Truth.
=> CORDA-3738: Tidy up class name resolution.

djvm/build.gradle, djvm/src/main/java/sandbox/java/math/BigDecimal.java, djvm/src/main/java/sandbox/java/math/BigInteger.java, djvm/src/main/kotlin/net/corda/djvm/analysis/AnalysisConfiguration.kt, djvm/src/main/kotlin/net/corda/djvm/analysis/JavaMathConfiguration.kt, djvm/src/main/kotlin/sandbox/java/lang/DJVM.kt, djvm/src/test/java/net/corda/djvm/execution/JavaMathTest.java
Add `BigInteger` and `BigDecimal` to the list of types that the DJVM can marshall into and out of the sandbox.
=> CORDA-3757: Add support for java.math.BigInteger and java.math.BigDecimal.

README.md, djvm-example/src/test/kotlin/com/example/testing/TestBase.kt, djvm/cli/src/main/kotlin/net/corda/djvm/tools/cli/ClassCommand.kt, djvm/cli/src/main/kotlin/net/corda/djvm/tools/cli/CommandBase.kt, djvm/secure/src/test/kotlin/com/example/testing/TestBase.kt, djvm/src/main/kotlin/net/corda/djvm/analysis/AnalysisConfiguration.kt, djvm/src/main/kotlin/net/corda/djvm/analysis/Whitelist.kt, djvm/src/test/java/net/corda/djvm/Utilities.java, djvm/src/test/kotlin/net/corda/djvm/TestBase.kt, djvm/src/test/kotlin/net/corda/djvm/analysis/ClassResolverTest.kt, djvm/src/test/kotlin/net/corda/djvm/analysis/WhitelistTest.kt, djvm/src/test/kotlin/net/corda/djvm/execution/SandboxExecutorTest.kt, djvm/src/test/kotlin/net/corda/djvm/rewiring/ByteCodeCacheTest.kt, djvm/src/test/kotlin/net/corda/djvm/source/SourceClassLoaderTest.kt
The DJVM's whitelist option is obsolete because the sandbox will almost certainly break if users tinker with the whitelist's contents. Conversely, there are situations when we may want to inject hand-written classes into the sandbox without their byte-code being rewritten.
Remove `whitelist` from the "root" `AnalysisConfiguration` options, and replace it with `overrideClasses`.
=> CORDA-3760: Replace whitelisting with override classes.

compiler-control.json, djvm/build.gradle
Make the compiler directives file more consistent with [compiler control documentation](https://docs.oracle.com/en/java/javase/11/vm/compiler-control1.html).
=> Standardise compiler directives for Java 11.

djvm/src/main/java/net/corda/djvm/rewiring/HostClassLoader.java, djvm/src/main/kotlin/net/corda/djvm/rewiring/SandboxClassLoader.kt
A `SandboxClassLoader` must ultimately have the DJVM's own application classloader as a parent so that it can load a sandbox's "foundation" classes. The standard classloader delegation mechanism would normally mean that multiple sandboxes would then complete for the `AppClassLoader`'s class-loading lock as they all tried to load the same non-sandbox classes at the same time.
Avoid this contention by creating `HostClassLoader` to handle requests for non-sandbox classes. This classloader leverages the JVM's native "lockless" cache of already loaded classes by invoking `Class.forName()` instead of `loadClass()`.
=> CORDA-3814: Fetch application classes from HostClassLoader.

djvm/src/main/kotlin/net/corda/djvm/source/SourceClassLoader.kt
A `ClassHeader` is a most superficial view of a class that describes only its superclass and any implemented interfaces. We do not need to visit any method byte-code or debug information to do this.
=> CORDA-3814: Visit as little byte-code as possible to create each ClassHeader.

.ci/Jenkinsfile, gradle.properties
This PR adds the Jenkinsfile necessary to migrate the TeamCity DJVM build to Jenkins. There are currently two TeamCity jobs configured for master and PR builds.
https://ci-master.corda.r3cev.com/project/CordaEnterprise_Sgx_Djvm?
Non-PR builds trigger publication to Artifactory.
Making a tag starting with `release/` publishes to `corda-dependencies` in Artifactory. Non-releases i.e. SNAPSHOTs will be published to `corda-dependencies-dev`.
https://ci01.dev.r3.com/job/DJVM/
=> INFRA-396 - Migrate DJVM build from TeamCity to Jenkins

djvm/build.gradle
Most of the `sandbox.*` classes are dummies and the rest aren't interesting to DJVM users.
=> NOTICK: Remove sandbox.* classes from source and JavaDoc.

djvm-example/gradle.properties, djvm-example/src/main/scala/com/example/testing/BadScalaTask.scala, djvm-example/src/main/scala/com/example/testing/ScalaDigestTask.scala, djvm-example/src/test/kotlin/com/example/testing/ScalaSandboxTest.kt, djvm/src/main/kotlin/net/corda/djvm/analysis/ClassAndMemberVisitor.kt, gradle.properties
Upgrade the following libraries for the DJVM:
- ASM 7.3.1 → 8.0.1
- Log4J2 2.13.1 → 2.13.3
- AssertJ 3.15.0 → 3.16.1
- ClassGraph 4.8.65 → 4.8.78
Example project:
- Corda 4.5-SNAPSHOT → 4.6-SNAPSHOT
- Kotlin 1.3.70 → 1.3.72
- Scala 2.13.1 → 2.13.3
- JUnit Jupiter 5.6.0 → 5.6.2
=> CORDA-3870: Upgrade libraries for 1.2

djvm/build.gradle, djvm/cli/build.gradle, djvm/src/main/kotlin/net/corda/djvm/analysis/ClassAndMemberVisitor.kt, djvm/src/main/kotlin/net/corda/djvm/analysis/SewingKit.kt, djvm/src/main/kotlin/net/corda/djvm/code/ClassDefinitionProvider.kt, djvm/src/main/kotlin/net/corda/djvm/code/ClassMutator.kt, djvm/src/main/kotlin/net/corda/djvm/code/MemberDefinitionProvider.kt, djvm/src/main/kotlin/net/corda/djvm/references/ClassInformation.kt, djvm/src/main/kotlin/net/corda/djvm/references/ClassRepresentation.kt, djvm/src/main/kotlin/net/corda/djvm/references/Member.kt, djvm/src/main/kotlin/net/corda/djvm/rules/ClassRule.kt, djvm/src/main/kotlin/net/corda/djvm/rules/InstructionRule.kt, djvm/src/main/kotlin/net/corda/djvm/rules/MemberRule.kt, djvm/src/main/kotlin/net/corda/djvm/rules/Rule.kt, djvm/src/main/kotlin/net/corda/djvm/rules/implementation/AlwaysInheritFromSandboxedObject.kt, djvm/src/main/kotlin/net/corda/djvm/rules/implementation/AlwaysUseNonSynchronizedMethods.kt, djvm/src/main/kotlin/net/corda/djvm/rules/implementation/AlwaysUseStrictFloatingPointArithmetic.kt, djvm/src/main/kotlin/net/corda/djvm/rules/implementation/DisallowOverriddenSandboxPackage.kt, djvm/src/main/kotlin/net/corda/djvm/rules/implementation/DisallowSandboxMethods.kt, djvm/src/main/kotlin/net/corda/djvm/rules/implementation/DisallowUnsupportedApiVersions.kt, djvm/src/main/kotlin/net/corda/djvm/rules/implementation/StaticConstantRemover.kt, djvm/src/main/kotlin/net/corda/djvm/rules/implementation/StubOutFinalizerMethods.kt, djvm/src/main/kotlin/net/corda/djvm/rules/implementation/StubOutIntrospectiveMethods.kt, djvm/src/main/kotlin/net/corda/djvm/rules/implementation/StubOutNativeMethods.kt, djvm/src/test/kotlin/net/corda/djvm/code/ClassMutatorTest.kt
Create immutable views for the `ClassRepresentation` and `Member` objects and update the `DefinitionProvider` classes to use them. This ensures that the DJVM can detect whenever a `DefinitionProvider` mutates an object by comparing the identities of the input and output.
This change merely formalises the existing behaviour, but it also allows us to optimise `ClassMutator`'s `DefinitionProvider` passes over all classes, methods and fields.
=> CORDA-3911: Optimise DefinitionProvider passes by using immutable objects.

djvm/cli/src/main/kotlin/net/corda/djvm/tools/cli/ClassCommand.kt, djvm/cli/src/main/kotlin/net/corda/djvm/tools/cli/RunCommand.kt
The CLI tool allows a user to transform a Java class into sandbox code as follows:
```
$ djvm build <class-name>
$ djvm run <class-name>
```
where `<class-name>` is the name of a class that implements `java.util.function.Function<?, ?>`. The only input value which can safely be passed into all implementations of `Function<T,R>.apply(T)` is `null`.
=> NOTICK: Update CLI to pass null as unused input parameter into user function.

djvm/bootstrap/build.gradle, djvm/build.gradle, gradle.properties, settings.gradle
Use `ShadowJar.archiveClassifier` now that it behaves correctly. This will make the Gradle build more consistent.
=> NOTICK: Update configuration for shadow plugin.

djvm/src/main/kotlin/net/corda/djvm/code/SyntheticAnnotationFactory.kt, djvm/src/test/java/net/corda/djvm/JavaAnnotationWithField.java, djvm/src/test/java/net/corda/djvm/execution/AnnotatedJavaClassTest.java, djvm/src/test/java/net/corda/djvm/execution/AnnotationProxyJavaTest.java
Annotations are interfaces, and so can also have `public static final` fields. These fields need to be deleted from the sandbox's synthetic `$1DJVM` annotations, along with any `<clinit>` function which initialises them.
=> CORDA-3923: Remove all static fields from synthetic annotation classes.

djvm/src/main/kotlin/net/corda/djvm/rewiring/SandboxClassLoader.kt, djvm/src/main/kotlin/net/corda/djvm/source/SourceClassLoader.kt
Convert any multi-release Jar URL into an unversioned one to ensure that the DJVM only selects byte-code for Java <= 8.
=> CORDA-3925: Add support for multi-release JARs of source classes.

build.gradle
Gradle 6.x seems to have started publishing Gradle metadata by default. I certainly didn't ask for that, and I don't believe anyone else did either, so turn it _OFF_ until someone actually does.
=> NOTICK: Don't publish Gradle metadata. "Keep it simple, stupid!"

djvm/cli/build.gradle, djvm/cli/src/main/kotlin/net/corda/djvm/tools/cli/BuildCommand.kt, djvm/cli/src/main/kotlin/net/corda/djvm/tools/cli/CheckCommand.kt, djvm/cli/src/main/kotlin/net/corda/djvm/tools/cli/ClassCommand.kt, djvm/cli/src/main/kotlin/net/corda/djvm/tools/cli/CommandBase.kt, djvm/cli/src/main/kotlin/net/corda/djvm/tools/cli/Commands.kt, djvm/cli/src/main/kotlin/net/corda/djvm/tools/cli/InspectionCommand.kt, djvm/cli/src/main/kotlin/net/corda/djvm/tools/cli/NewCommand.kt, djvm/cli/src/main/kotlin/net/corda/djvm/tools/cli/RunCommand.kt, djvm/cli/src/main/kotlin/net/corda/djvm/tools/cli/ShowCommand.kt, djvm/cli/src/main/kotlin/net/corda/djvm/tools/cli/TreeCommand.kt, djvm/cli/src/main/kotlin/net/corda/djvm/tools/cli/Utilities.kt
Only the DJVM itself needs to be compiled with Kotlin 1.2. The CLI can safely be updated to use Kotlin 1.3.
=> NOTICK: Upgrade the DJVM CLI to use the Kotlin 1.3 runtime libraries.

build.gradle, deterministic-rt/build.gradle, deterministic-rt/gradle.properties, djvm-example/build.gradle, djvm-example/gradle.properties, djvm/build.gradle, djvm/osgi/build.gradle, gradle.properties
Stop relying on Gradle behaviour that will be removed in Gradle 7.0.
=> NOTICK: Update Gradle scripts and resolve warnings.

djvm-example/build.gradle, djvm/build.gradle, djvm/cli/build.gradle, djvm/osgi/build.gradle, djvm/secure/build.gradle, gradle.properties, settings.gradle
Update the Gradle build scripts:
- Shadow plugin 6.0.0 -> 6.1.0
- Artifactory plugin: 4.17.1 -> 4.17.2
- More concise references to SourceSets.
- Use "lazy" task references in artifacts block.
=> NOTICK: Update Gradle usage,

djvm-example/gradle.properties, gradle.properties
Test against Corda 4.8-SNAPSHOT rather than 4.7-SNAPSHOT.
=> NOTICK: Upgrade Corda artifacts to 4.8-SNAPSHOT for testing.

djvm/cli/src/main/kotlin/net/corda/djvm/tools/cli/ClassCommand.kt, djvm/src/main/java/sandbox/java/lang/DJVMClassLoader.java, djvm/src/main/kotlin/net/corda/djvm/rewiring/Predicates.kt, djvm/src/main/kotlin/net/corda/djvm/rewiring/SandboxClassLoader.kt, djvm/src/main/kotlin/sandbox/java/lang/DJVM.kt, djvm/src/test/java/net/corda/djvm/execution/SandboxObjectTest.java
Java recommends loading classes via `Class.forName()` rather than `ClassLoader.loadClass()` because `Class.forName()` can return an already-loaded class without taking any locks. Sandboxes are single-threaded, so this change will be most significant when loading the shared white-listed classes. The rest is just "good practice".
=> NOTICK: Prefer Class.forName() over ClassLoader.loadClass().

djvm/osgi/build.gradle
The OSGi module is only used to run tests inside an OSGi framework. There is no public API to scan, and nothing to publish afterwards.
=> NOTICK: Remove unused publication and API plugins from OSGi module.

settings.gradle
The Enterprise plugin allows us to perform build scans.
=> NOTICK: Upgrade Gradle Enterprise plugin 3.4.1 -> 3.6.

build.gradle
Configure the `JavaCompile` tasks alongside the other compilation tasks.
=> NOTICK: Only set the toolchain inside the AppliedPlugin handler.

deterministic-rt/build.gradle, djvm-example/build.gradle, djvm-example/gradle.properties, djvm/build.gradle, djvm/osgi/build.gradle, djvm/osgi/test.bndrun, djvm/secure/build.gradle, gradle.properties
Update dependencies:
- Corda 4.8 -> 4.8.1
- SLF4J 1.7.30 -> 1.7.32
- JUnit 5.7.0 -> 5.7.2
Use Gradle variant attribute to select jar artifact over classes for testing, and configure task dependencies more correctly.
=> NOTICK: Update dependency versions and Gradle usage.

djvm/src/main/kotlin/net/corda/djvm/analysis/AnalysisConfiguration.kt, djvm/src/main/kotlin/net/corda/djvm/rewiring/SandboxClassLoader.kt, djvm/src/main/kotlin/sandbox/TaskTypes.kt, djvm/src/test/kotlin/net/corda/djvm/execution/ImportSupplierTaskTest.kt, djvm/src/test/kotlin/net/corda/djvm/execution/ImportTaskTest.kt
The idea is that suppliers can provide sandbox objects that have been created outside the sandbox via other means, and so make it easier to build complex structures inside the sandbox.
=> NOTICK: Add ImportSupplierTask to wrap Supplier instances for importing.

buildSrc/src/main/groovy/djvm-publish.gradle, djvm/build.gradle
Simplify publishing the DJVM by creating a new "djvm" `SoftwareComponent` to generate the correct POM.
=> NOTICK: Create Gradle SoftwareComponent for publishing.
